config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 Folder_Python
        container: qc.sty_messy-peach-loon
timeout: 5400
